### ISSUE TITLE
Icons not displayed

### ISSUE THREAD

**Issue by NolwennR** [xwikisas/application-diagram#203] opened 2021-07-05 16:56 UTC
Hi,  somes packages of icons are not displayed neither in the icons bar nor on the panel. For example none of the "Azure" icons are displayed but "google cloud plateform" 's are.

We are using version 1.16.2 of application diagram and version 12.10.6 of XWiki.

![Image1](https://user-images.githubusercontent.com/35705805/124501367-afa22d80-ddc1-11eb-984f-94b98ed0fd22.png)

**Comment by oanalavinia** [comment] 2021-07-06 06:08
Hi!
There is already an issue opened for this and we are working on it #182 
I'll close this as duplicate, but I will let you know when the problem is fixed

**Closed by oanalavinia** 2021-07-06 06:08 UTC

**Comment by oanalavinia** [comment] 2021-09-07 09:08
Hi! The issue is fixed in  Diagram Application (Pro) version [1.17](https://store.xwiki.com/xwiki/bin/view/Extension/DiagramApplication#versions)
