### ISSUE TITLE
Can't import a diagram

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-diagram#6] opened 2018-08-10 09:20 UTC
Please see the following [JIRA](https://jira.xwiki.org/browse/XADIAGRAM-37) issue.

However, on Chrome, if clicked Import from > Device..., to import a XML file (which was previously exported from draw.io for example), the diagram is imported properly.

**Comment by mflorea** [comment] 2018-08-24 07:41
I fixed the open form (Import from > Browser...). As for the import from device, it seems to work on Firefox also. The import from URL behaves now exactly as on draw.io. I'm closing this issue for now.

**Closed by mflorea** 2018-08-24 07:41 UTC
Labels: Priority: Blocker, Type: Bug

**Comment by VGerris** [comment] 2025-06-12 01:56
this doesn't seem to work on recent versions ( Xwiki 17.4.0 ). Perhaps because some shapes are missing.

**Comment by petrenkonikita112263** [comment] 2025-06-12 11:30
Hello @VGerris if you encounter an issue with an extension on the latest version of XWiki, it's best to report it as a new issue rather than commenting on an already resolved one. The issue might not yet be known (i.e current [open issues](https://github.com/xwikisas/application-diagram/issues)). Remember to include detailed reproduction steps, screenshots, and relevant logs (as long as they don’t contain any private or sensitive information)

Also, remember if you're having issue with purchased the extension, your license includes a support contract for professional help [XWiki SAS](https://xwiki.com/en/company/contact-us).
