### ISSUE TITLE
"Unknown property meta class field" appears in logs when uninstalling the Diagram PRO app on 9.11

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#191] opened 2021-04-23 16:18 UTC
When uninstalling Diagram Application (Pro) 1.16-rc-2 on XWiki 9.11 the following warnings appear in the log:

```Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [DBList]
Unknown property meta class field [freeText] for property type [DBList]
Unknown property meta class field [largeStorage] for property type [DBList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [defaultValue] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
Unknown property meta class field [freeText] for property type [StaticList]
Unknown property meta class field [largeStorage] for property type [StaticList]
```

![UnknownProperty](https://user-images.githubusercontent.com/40691112/115900160-4ff5e080-a468-11eb-85c8-a09267ffd7ed.png)

Environment: Windows 10, XWiki 9.11, Chrome 89, Diagram Application (Pro) 1.16-rc-2

**Comment by mflorea** [comment] 2021-04-26 08:29
@ane-gabriela you need to give us more details (e.g. the logs before the warning messages) because the Diagram application doesn't use the ``freeText`` meta property nor the ``largeStorage`` meta property so this must come from something else but it's hard to know without having the logs before the warning (i.e. to know at what uninstall step were these messages logged).

**Comment by ane-gabriela** [comment] 2021-04-26 12:10
Unfortunately I don't have the full logs anymore. I've used a clean 9.11 instance to test Diagram Application (Pro) 1.16-rc-2, I've created many diagrams and added all types of shapes.
I've reinstalled the diagram app on the 9.11 instance again but I don't get the warning messages when uninstalling it anymore.

**Comment by petrenkonikita112263** [comment] 2023-02-14 12:23
**Minimal XWiki version supported: XWiki 11.10**

**Comment by mflorea** [comment] 2023-02-22 11:41
@petrenkonikita112263 if you don't reproduce with 11.10 then we can close this issue as Cannot Reproduce.

**Comment by petrenkonikita112263** [comment] 2023-04-07 06:37
![msedge_RxkZnGuSM0](https://user-images.githubusercontent.com/56109799/230555366-ff5dd91b-499b-4c39-a74c-f1db54190030.gif)

Can't reproduce

**Closed** 2023-11-22 12:31 UTC
Labels: Priority: Minor, Status: Cannot Reproduce, Type: Bug
