### ISSUE TITLE
Errors in browser and XWiki console

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#74] opened 2019-09-26 13:09 UTC
Testing on cloud instance (10.11.9) with Chrome 77 and when Editing a diagram, errors appear in the browser console
![CloudBrowserConsole](https://user-images.githubusercontent.com/40691112/65689919-9f9add00-e076-11e9-9052-c842b5b128e8.jpg)

Also tested on XWiki 11.8 RC1 with MySQL 5.7, IE 11 and got errors in the XWiki console and in the browser console:

![IE11XWiki11 8RC1](https://user-images.githubusercontent.com/40691112/65690532-eccb7e80-e077-11e9-892a-cbc35af45f66.jpg)

`2019-09-26 15:46:16,317 [http://localhost:8080/xwiki/bin/jsx/Diagram/DiagramEditSheet?language=en&docVersion=1.1] WARN  c.x.x.w.s.JsExtension          - Error at line 2, column 2: syntax error. Caused by: [*/]
2019-09-26 15:46:16,323 [http://localhost:8080/xwiki/bin/jsx/Diagram/DiagramEditSheet?language=en&docVersion=1.1] ERROR c.x.x.w.s.JsExtension          - Runtime error minimizing JSX object: Compilation produced 1 syntax errors.
2019-09-26 15:46:16,323 [http://localhost:8080/xwiki/bin/jsx/Diagram/DiagramEditSheet?language=en&docVersion=1.1] WARN  c.x.x.w.s.JsExtension          - Failed to compress JS extension: null
2019-09-26 15:47:56,144 [http://localhost:8080/xwiki/bin/jsx/Diagram/DiagramViewSheet?language=en&docVersion=1.1] WARN  c.x.x.w.s.JsExtension          - Error at line 2, column 2: syntax error. Caused by: [*/]
2019-09-26 15:47:56,146 [http://localhost:8080/xwiki/bin/jsx/Diagram/DiagramViewSheet?language=en&docVersion=1.1] ERROR c.x.x.w.s.JsExtension          - Runtime error minimizing JSX object: Compilation produced 1 syntax errors.
2019-09-26 15:47:56,147 [http://localhost:8080/xwiki/bin/jsx/Diagram/DiagramViewSheet?language=en&docVersion=1.1] WARN  c.x.x.w.s.JsExtension          - Failed to compress JS extension: null`

**Comment by mflorea** [comment] 2019-09-30 15:12
There are 2 errors logged but they don't have any effect for the end user:
* the blocked request for real-time update just means the real-time update feature is not going to be used (we removed it from the menus also)
* The XML request is thrown only on Firefox. I haven't found the root cause.

**Comment by acotiuga** [comment] 2020-11-13 12:51
@mflorea can we close this issue? It looks like the XML request error was reported again in #136 so we can fix it there.

**Comment by mflorea** [comment] 2020-12-05 12:15
For the JavaScript error messages there is #136 still open.

**Closed by mflorea** 2020-12-05 12:15 UTC
Labels: Priority: Trivial, Type: Bug
