### ISSUE TITLE
Uncached diagrams that contain links or Heading shapes aren't shown in View mode in an AWM

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#139] opened 2020-04-15 09:41 UTC
Preconditions: Import the diagrams attached

Steps to reproduce:

1. Create a an AWM which contains Content field
2. Add an entry
3. In the Content field add the Diagram Macro
4. Add the Diagram in Reference eg. "Diagram.Diagram 4.WebHome"
5. **Uncheck** the Cached option
6. Submit the macro
7. Save & View the page

Expected results: The diagram is properly shown.

Actual results: The diagram is shown for 1-2 seconds, then it vanishes.
This happens when I have diagrams with links or when there is a Heading shape inserted.

Environment: Windows 10, XWiki 11.10.4 with MySQL 5.7 and Chrome 81

https://up1.xwikisas.com/#xGanfN3yoRaNw9QvtUJc8w - Video

https://up1.xwikisas.com/#fw-E6TYGrJSQ9eg0EPbTvA - Diagram with links

https://up1.xwikisas.com/#UqQQuiEca1qe4sZU8XbijA - Diagram with Heading

**Comment by ane-gabriela** [comment] 2020-04-15 12:17
Working on XWiki 9.11

**Comment by mflorea** [comment] 2020-04-16 08:47
Duplicate of #122.

**Closed by mflorea** 2020-04-16 08:47 UTC
Labels: Priority: Major, Status: Duplicate, Type: Bug
