### ISSUE TITLE
Diagram does not scale when zooming on page in view mode

### ISSUE THREAD

**Issue by slauriere** [xwikisas/application-diagram#31] opened 2019-03-28 08:58 UTC
When zooming on a page in view mode containing a diagram, the diagram does not scale with the rest of the page, while it does in edit mode. This behaviour was reproduced with Firefox and Chrome.

**Comment by mflorea** [comment] 2019-09-11 13:16
@slauriere I can't reproduce. The browser zoom works fine for me in both Firefox and Chrome. I'm closing this since we're going to implement #32 soon anyway.

**Closed by mflorea** 2019-09-11 13:16 UTC
Labels: Priority: Minor, Status: Cannot Reproduce

**Comment by slauriere** [comment] 2019-09-11 13:44
Thanks for trying, I just gave a new try with an updated Firefox (version 69.0 on Ubuntu) and I still face the issue, only in view mode. I wish I could attach a video capture but there's a bug with the Peek gif recorder on my machine, so I'm just attaching screenshots for the record. It seems the browser scales correctly in a first step, then immedialtely scales down, while everything's ok in edit mode. Possibly an issue with my settings, it's weird. Anyway #32 will be a better approach for this functionality indeed

![zoom-100%](https://user-images.githubusercontent.com/1022195/64702541-059a3880-d4ab-11e9-97c5-a8d1dfbbb356.jpg)
![zoom-140%](https://user-images.githubusercontent.com/1022195/64702542-059a3880-d4ab-11e9-9725-7e6ff038382d.jpg)

.
