### ISSUE TITLE
Links are not working when displaying a diagram on a different page

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-diagram#230] opened 2022-11-09 13:47 UTC
Steps to reproduce on XWiki 14.4.6 with Diagram Pro 1.17.3:

1. Install the Diagram Pro 1.17.3 and get a trial license
2. Create a diagram "DiagramTest"and add a text and a link to it from the Text right section
<img width="500" alt="image" src="https://user-images.githubusercontent.com/36840106/200846187-85ece14e-1b8e-42fe-ad77-e99124b0d39c.png">
3. Save and go to a different XWiki page like Sandbox TestPage1
4. Insert the diagram macro and add the new diagram reference, in this case Diagram.DiagramTest.WebHome

**Expected result**:
A displayed diagram with working links

**Actual result**:
A displayed diagram with text only instead of a working link on the text
<img width="500" alt="image" src="https://user-images.githubusercontent.com/36840106/200846686-f2eea1a7-dbe2-49d7-8c25-fcf32df75f8d.png">

**Comment by ilieandriuta** [comment] 2022-11-15 13:23
I've reproduced the issue too on Diagram 1.17.3 on XWiki 14.9 (w Edge 107/ PostgreSQL 15/ Tomcat 9.0.68). 

I've noticed that the issue reproduces also for external links, not only for internal ones.

**Comment by oanalavinia** [comment] 2022-11-24 15:00
Note that this is the case only when the `cached` option is checked

**Comment by oanalavinia** [comment] 2023-01-09 14:45
Closing the issue since this is the expected behavior when using the cached option, since an image is actually displayed

**Closed by oanalavinia** 2023-01-09 14:45 UTC
Labels: Priority: Major, Type: Bug

**Comment by oanalavinia** [comment] 2023-01-09 14:48
> In XWiki console, there is the following stacktrace (but doesn't reproduce consistently it seems):

@ilieandriuta you can open a new issue for this error, it's not linked to the issue
