### ISSUE TITLE
Preview from "Export as URL" is not working

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#57] opened 2019-08-26 14:29 UTC
Steps to reproduce:

1. Edit a Diagram
2. Click on File > Export as > URL...
3. Click on the Create button
4. Click on Preview

Expected results: The diagram appears as a preview.

Actual results: "http:localhost:8080/xwiki/bin/view/Diagram/DiagramViewSheet?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Diagram1&source=url#RvZdds5owEIZ%2FjbcdIIL0Vo89vWinZ8aLtpcRFkhPYJm4KPbXN0iUz1Y6g95o9l3y9ewmLAu2SctXxfPkK4YgF44Vlgv2snAcZvv6txLOteBadi3ESoS11BJ24jcY0TJqIUI4dB4kREki74oBZhkE1NG4UnjqPhah7M6a8xgGwi7gcqh%2BFyElRrW9j43jM4g4MVP7zqp27HnwHissMjNfhhnUnpRfhzF7PCQ8xFNLYtsF2yhEqltpuQFZUb0Sq%2Ft9%2Bov3tmQFGU3p4NQdjlwWZtdmXXS%2BYtAdNHFtrE%2BJINjlPKg8Jx1zrSWUSm3ZuskPeR2GSJSgx19HQsoNSlSXgVgURU4QaP1ACt%2Bh5Qm9ved62jNcvtnRERRB2ZLMdl4BUyB11o8Y75XsuWuemgj6RkrasTMaNzkT38Zt4OmG4TfOkt1nqcOdV02REaiMyx2humThPbZNSn0rSIoMjN5DHHLwo1HEXuDDPpoHsb3qMl4%2Bj%2FFyOmO6%2FN0D289RP4DxHN377tK1ZgLo9ZKUDQnazghC25qBofvIMz8DnR4cxtgH92kJ5t2HQ0rwLJYT6MwAY9k%2FasNM8R6EYvU%2FeXI9dYHEInwKGZv18sSdeIjmYONPv4f0JrmUIDFWPNVbz0EJPR%2Bovu%2BtcTwDX%2B%2BY2SO3%2BCg%2BbwZ8tj1MpVAXX8ZERQnGqF%2BQ20ZdX15%2F1SXzYnVpQCnoRyXre6K2fhrPLyA6m8qSF4Raasb%2Bgpjf43nAQgW9urRa6T8JK5CcxLFbRo7hMl3fUNcDrcj0SxinR5y4ioFMrx702zKmxcGansez1Szz34r246o8bTbVeE24%2Bdhh2z8%3D" appears.

Environment: Windows 10, XWiki 8.4.5 Standard and IE11

Linked to: https://github.com/xwikisas/application-diagram/issues/24

![Preview](https://user-images.githubusercontent.com/40691112/63698335-506b4d80-c827-11e9-8be8-78978e35a55d.jpg)

**Comment by arcilli** [comment] 2019-08-27 07:10
The problem is generated by missing '//' after protocol, which was fixed in #56.

**Comment by mflorea** [comment] 2019-08-27 12:06
Duplicate of #55 , will be fixed in version 1.7.1.

**Closed by mflorea** 2019-08-27 12:06 UTC
Labels: Priority: Major, Status: Duplicate, Type: Bug
