### ISSUE TITLE
SVG attachment not saved on first Save & View

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#93] opened 2019-11-28 12:55 UTC
Steps to reproduce:

1. Create a new diagram
2. Add some shapes
3. Save & View

Expected results: The SVG is saved as attachment.

Actual results: No SVG appears.

Environment: Windows 10, XWiki 8.4.5 with Chrome 78, Diagram v 1.11

![NoSVGAttachment](https://user-images.githubusercontent.com/40691112/69807889-15decb80-11ef-11ea-8d0f-0be730b1075b.jpg)

**Comment by ane-gabriela** [comment] 2019-11-28 13:04
Also, got https://up1.xwikisas.com/#o0lxzIBekkDRf-C7RZAKfA in the XWiki Console

**Comment by mflorea** [comment] 2019-11-29 10:45
> Also, got https://up1.xwikisas.com/#o0lxzIBekkDRf-C7RZAKfA in the XWiki Console

@ane-gabriela doesn't seem related.

I can't reproduce with XWiki 11.10 on Firefox. This might be:

* an issue on older versions of XWiki (8.4.x), @ane-gabriela can you reproduce on a recent version of XWiki?
* an issue on Chrome, @ane-gabriela can you reproduce with Firefox?
* a synchronization issue, like if the SVG upload request is send at the same time as the save request and the save request overwrites the attachment upload. @ane-gabriela check if there are multiple versions created in the page history when the diagram is saved for the first time. You could also check if the SVG upload request is sent by looking at the network tab

**Comment by ane-gabriela** [comment] 2019-12-02 10:59
- Tested on 11.3.6 and it is working, the SVG is saved as attachment from the first Save & View. 2 versions saved in History

![WorkingOn11 3 6](https://user-images.githubusercontent.com/40691112/69954200-7463bc80-1503-11ea-9eb8-b6a766f42c69.jpg)


- I can reproduce on Firefox 70 with version 8.4.5

![Firefoxjpg](https://user-images.githubusercontent.com/40691112/69954227-7f1e5180-1503-11ea-9820-d5a0007ad33b.jpg)



- 2 versions are saved in History

![2VersionsCreatedinHistory](https://user-images.githubusercontent.com/40691112/69954242-847b9c00-1503-11ea-9ba8-917af0d9b288.jpg)

**Comment by mflorea** [comment] 2019-12-02 11:35
Thanks @ane-gabriela . So this looks like a synchronization issue (the save request doesn't wait for the upload request to finish) and it affects only older versions of XWiki (8.4.5), no matter the browser.

**Comment by oanalavinia** [comment] 2020-03-31 08:17
This is related to https://jira.xwiki.org/browse/XWIKI-14204 and was fixed by updating the xwiki parent to 9.11 in #97

**Closed by oanalavinia** 2020-03-31 08:17 UTC
Labels: Priority: Critical, Type: Bug
